[package]
name = "peregrine-scheduler"
version = "0.1.0"
edition.workspace = true

[dependencies]
peregrine-api = { workspace = true }
peregrine-engine-http = { workspace = true }
peregrine-engine-hls = { workspace = true }
peregrine-engine-ftp = { workspace = true }
peregrine-storage = { workspace = true }
peregrine-task-manager = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt", "time", "macros"] }
tokio-util = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
axum = { workspace = true }
tempfile = { workspace = true }
